'use strict';
/* ============ AI LAYER (Gemini via the Bitewise server) ============ */
/* Hosted app: window.BITEWISE_CONFIG (from /config.js) → talk to the Bitewise server. */
const CFG=window.BITEWISE_CONFIG||null,API=CFG?(CFG.apiBase||''):'';
let AIH,AIERR='',HEALTH=null;
const canAI=()=>!!CFG;
const toB64=b=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]);r.onerror=rej;r.readAsDataURL(b)});
async function apiPost(path,body){let r;try{r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}catch(e){throw{code:'offline',message:'Can’t reach the Bitewise server.'}}
 let j={};try{j=await r.json()}catch(e){}if(!r.ok)throw{code:({429:'rate_limited',413:'image_rejected',503:'unavailable',400:'invalid_request'})[r.status]||'upstream_error',message:j.error||'The server had a problem. Try again.'};return j}
async function ai(){if(AIH)return AIH;if(!CFG){AIERR='AI is available after Bitewise is published.';return null}
 AIH={limits:async()=>({images:{}}),json:async(prompt,o={})=>{const body={prompt,tier:o.modelTier==='quick'?'quick':'default'};if(o.images){const b=Array.isArray(o.images)?o.images[0]:o.images;body.image={media_type:b.type||'image/jpeg',data:await toB64(b)}}return(await apiPost('/api/ai',body)).data}};return AIH}
const aiMsg=e=>({offline:'You seem to be offline — AI needs a connection. Manual logging still works.',not_granted:'AI access was declined — you can still add everything manually.',rate_limited:'AI is busy or your usage limit is reached. Try again later or add manually.',images_unavailable:'Photos can’t be sent to AI in this view.',image_rejected:'That image couldn’t be read. Try another photo.',invalid_json:'AI replied in a format I couldn’t read. Try again.'}[e?.code]||e?.message||'AI couldn’t answer just now.');
async function aiJson(prompt,opts){const sm=await ai();if(!sm)throw{code:'unavailable',message:AIERR||'AI is not available in this view — manual logging still works.'};return sm.json(prompt,opts)}
const num=v=>{v=+v;return isFinite(v)?Math.max(0,v):0};
async function prepImage(file,max=1280){let bmp;try{bmp=await createImageBitmap(file)}catch(e){bmp=await new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=URL.createObjectURL(file)})}
 const w=bmp.width||bmp.naturalWidth,h=bmp.height||bmp.naturalHeight,s=Math.min(1,max/Math.max(w,h)),c=document.createElement('canvas');c.width=Math.round(w*s);c.height=Math.round(h*s);c.getContext('2d').drawImage(bmp,0,0,c.width,c.height);
 const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.85));const sm=document.createElement('canvas');sm.width=9;sm.height=8;const x=sm.getContext('2d');x.drawImage(c,0,0,9,8);const d=x.getImageData(0,0,9,8).data;
 const gray=i=>d[i*4]*.3+d[i*4+1]*.59+d[i*4+2]*.11;let hash='';for(let r=0;r<8;r++)for(let q=0;q<8;q++)hash+=gray(r*9+q)>gray(r*9+q+1)?'1':'0';
 const t=document.createElement('canvas');t.width=64;t.height=64;const tc=t.getContext('2d'),m=Math.min(w,h);tc.drawImage(bmp,(w-m)/2,(h-m)/2,m,m,0,0,64,64);
 return{blob,url:URL.createObjectURL(blob),hash,thumb:t.toDataURL('image/jpeg',.6)}}
const ham=(a,b)=>{let d=0;for(let i=0;i<a.length;i++)if(a[i]!==b[i])d++;return d};
function qtyFor(f,g){const u=f.units[0];if(u.l==='g'||u.l==='ml')return Math.max(5,Math.round(g/5)*5);const q=g/u.g;return q<1?Math.max(.25,Math.round(q*4)/4):Math.round(q*2)/2}
function dbIdList(){return ALLFOODS().map(f=>f.id+'='+f.name).join('; ')}
function aiItemToPlate(it){let f=it.dbId&&F(it.dbId);const grams=num(it.grams)||100;
 if(!f){const p=it.per100||{};f={id:'t_'+uid(),name:String(it.name||'Food').slice(0,60),alias:'',cat:'cust',veg:'V',kind:'h',meals:'',n100:Object.assign(zeroN(),{kcal:num(p.kcal),p:num(p.p),c:num(p.c),f:num(p.f),fib:num(p.fib),sug:num(p.sug),na:num(p.na)}),mods:[],units:[{l:'g',g:1}],def:grams,col:'B0B4C8',src:'ai'};S.tfoods[f.id]=f;return{fid:f.id,qty:Math.max(5,Math.round(grams/5)*5),unit:'g',mods:{},ai:{name:it.name,dbId:null,grams,conf:it.confidence||'medium',note:it.note}}}
 const pp=S.learn.portions[f.id],q=qtyFor(f,grams);return{fid:f.id,qty:q,unit:f.units[0].l,mods:defMods(f,q*f.units[0].g),ai:{name:it.name||f.name,dbId:f.id,grams,conf:it.confidence||'medium',note:it.note}}}

/* ============ CUSTOM FOOD FORM (AI estimate / manual / label) ============ */
let FM=null;
ACT.newFood=()=>{FM={name:'',veg:'V',g:100,v:{},mic:{},src:'user',text:UI.q||'',ing:'',basis:'',conf:'',busy:false,err:''};openSheet('Add food','','');renderForm()};
ACT.editFood=t=>{const f=F(t.dataset.id);const g=f.units[0].g>1?f.units[0].g:100;FM={name:f.name,veg:f.veg,g,v:Object.fromEntries(['kcal','p','c','f','fib','sug','na'].map(k=>[k,r1(f.n100[k]*g/100)])),mic:Object.fromEntries(MK.map(k=>[k,f.n100[k]*g/100])),src:f.src==='pack'?'user':f.src,text:'',ing:f.ing||'',basis:f.basis||'',conf:'',editId:f.id,barcode:f.barcode};LOG=null;openSheet('Edit food','','');renderForm()};
function openForm(o){FM=Object.assign({name:'',veg:'V',g:100,v:{},mic:{},src:'user',text:'',ing:'',basis:'',conf:'',busy:false,err:''},o);openSheet(FM.src==='label'?'Check the label values':'Confirm food','','');renderForm()}
function renderForm(){const M=FM,fld=(k,l,u)=>`<label class="field" style="margin:0"><span>${l}</span><input class="inp" type="number" inputmode="decimal" step="any" value="${M.v[k]??''}" data-in="fv" data-k="${k}" placeholder="0"></label>`;
 const est=M.src==='ai';
 $('#shb').innerHTML=`${!M.editId&&M.src!=='label'?`<div class="card"><div class="b">Describe it</div><textarea class="inp" style="margin-top:8px" placeholder="e.g. Homemade paneer tikka, 150 grams" data-in="ftext">${esc(M.text)}</textarea>
  <button class="btn full" style="margin-top:10px" data-act="fEstimate" ${M.busy?'disabled':''}>${M.busy?'<span class="spin"></span> Estimating…':'Estimate with AI'}</button>${M.err?`<div class="note sm" style="margin-top:8px">${esc(M.err)}</div>`:''}<p class="xs mut" style="margin:8px 0 0">${CFG?'AI estimates using nutrition databases (Open Food Facts and Google Search) plus typical values. You confirm every number before anything is added.':'AI estimates from typical nutrition data — it does not browse the web. You confirm every number before anything is added.'}</p></div><div class="c mut sm" style="margin:12px 0">— or fill in by hand —</div>`:''}
 ${est?`<div class="note sm"><span class="badge ai">AI estimate</span> ${esc(M.basis||'')}${M.refs&&M.refs.length?`<br><span class="xs">Reference data used: ${M.refs.map(r=>esc(r.name)+' ('+esc(r.source)+')').join('; ')}</span>`:''}${M.conf?` · confidence: <b>${esc(M.conf)}</b>`:''}<br>Please check the numbers below, edit anything that looks off, then continue.</div>`:''}
 ${M.src==='label'?`<div class="note sm"><span class="badge ok">From label</span> ${esc(M.basis||'')}<br>Check these against your pack — OCR can misread digits.</div>`:''}
 <label class="field"><span>Food name</span><input class="inp" value="${esc(M.name)}" data-in="fname" placeholder="e.g. Homemade paneer tikka"></label>
 <div class="opts" style="margin-top:10px">${[['V','Vegetarian'],['E','Has egg'],['N','Non-veg']].map(([k,l])=>`<button class="opt ${M.veg===k?'on':''}" data-act="fveg" data-v="${k}">${l}</button>`).join('')}</div>
 <label class="field"><span>Serving size these numbers are for (g or ml)</span><input class="inp" type="number" inputmode="decimal" value="${M.g}" data-in="fg"></label>
 <div class="grid2" style="margin-top:12px">${fld('kcal','Calories (kcal)')}${fld('p','Protein (g)')}${fld('c','Carbs (g)')}${fld('f','Fat (g)')}${fld('fib','Fibre (g)')}${fld('sug','Sugar (g)')}${fld('na','Sodium (mg)')}</div>
 ${Object.keys(M.mic).length?`<details class="dt"><summary>Vitamins & minerals</summary><table class="nt">${MK.map(k=>`<tr><td>${MNAME[k][0]}</td><td>${r1(M.mic[k]||0)} ${MNAME[k][1]}</td></tr>`).join('')}</table></details>`:''}
 ${M.src==='label'?`<label class="field"><span>Ingredients</span><textarea class="inp" data-in="fing">${esc(M.ing)}</textarea></label>`:''}`;
 $('#shf')?.remove();$('.sheet').insertAdjacentHTML('beforeend',`<div class="sh-f" id="shf"><button class="btn ghost" data-act="fGo" data-save="0">Log once</button><button class="btn" data-act="fGo" data-save="1">Save & continue</button></div>`)}
INP.ftext=t=>{FM.text=t.value};INP.fname=t=>{FM.name=t.value};INP.fg=t=>{FM.g=num(t.value)||100};INP.fv=t=>{FM.v[t.dataset.k]=t.value};INP.fing=t=>{FM.ing=t.value};
ACT.fveg=t=>{FM.veg=t.dataset.v;const sc=$('#shb').scrollTop;renderForm();$('#shb').scrollTop=sc};
async function estimateViaServer(M){const o=await apiPost('/api/estimate',{text:M.text});M.refs=o.refs||[];return o.data}
ACT.fEstimate=async()=>{const M=FM;if(!M.text.trim())return;M.busy=true;M.err='';renderForm();
 try{const r=CFG?await estimateViaServer(M):await aiJson(`You are a nutrition assistant for Indian food. Estimate the nutrition of: "${M.text.replace(/"/g,"'")}".\nIf a weight or volume is given, use it; otherwise assume one typical serving. Assume home-style Indian preparation unless a restaurant/packaged item is stated. You cannot browse the web — use your knowledge of typical values, and say so honestly in "basis".\nReply ONLY with JSON: {"name":string,"grams":number,"veg":"V"|"E"|"N","values":{"kcal":number,"p":number,"c":number,"f":number,"fib":number,"sug":number,"na":number},"micros":{"fe":number,"ca":number,"vA":number,"b12":number,"vC":number,"vD":number,"fol":number,"mg":number,"k":number,"zn":number},"basis":string,"confidence":"high"|"medium"|"low"}\nAll values are for the whole stated serving; sodium and minerals in mg, vitamin A/B12/D/folate in µg, vitamin C in mg.`,{modelTier:'quick'});
  Object.assign(M,{name:r.name||M.text,g:num(r.grams)||100,veg:['V','E','N'].includes(r.veg)?r.veg:'V',v:Object.fromEntries(['kcal','p','c','f','fib','sug','na'].map(k=>[k,r1(num(r.values?.[k]))])),mic:Object.fromEntries(MK.map(k=>[k,num(r.micros?.[k])])),basis:r.basis||'',conf:r.confidence||'medium',src:'ai',busy:false})}
 catch(e){M.busy=false;M.err=aiMsg(e)}renderForm();$('.sheet .note')?.scrollIntoView({block:'start'})};
ACT.fGo=t=>{const M=FM;if(!M.name.trim())return toast('Give the food a name');const g=M.g||100;if(!num(M.v.kcal)&&!num(M.v.p)&&!num(M.v.c)&&!num(M.v.f))return toast('Enter at least calories or macros');
 const per=k=>num(M.v[k])*100/g,n100=Object.assign(zeroN(),{kcal:per('kcal'),p:per('p'),c:per('c'),f:per('f'),fib:per('fib'),sug:per('sug'),na:per('na')});MK.forEach(k=>n100[k]=num(M.mic[k])*100/g);
 const save=t.dataset.save==='1',id=M.editId||(save?'c_':'t_')+uid();const food={id,name:M.name.trim().slice(0,60),alias:'',cat:'cust',veg:M.veg,kind:M.src==='label'?'p':'h',meals:'',n100,mods:[],units:[{l:`serving (${r0(g)} g)`,g},{l:'g',g:1}],def:1,col:M.veg==='N'?'C97A5A':'B9B0D8',src:M.src,basis:M.basis,ing:M.ing,barcode:M.barcode};
 if(M.editId){const i=S.foods.findIndex(x=>x.id===id);if(i>=0)S.foods[i]=food;else S.tfoods[id]=food}else if(save)S.foods.push(food);else S.tfoods[id]=food;save_();const o={date:vd};FM=null;LOG=null;openLog(food,o)};
const save_=()=>save();

/* ============ SCAN ============ */
const PROVIDERS={off:{name:'Open Food Facts',status:'untested',async lookup(code){if(CFG){try{const r=await fetch(API+'/api/barcode/'+encodeURIComponent(code));if(!r.ok)throw 0;this.status='connected';return await r.json()}catch(e){this.status='unreachable';return{error:'unreachable'}}}const c=new AbortController(),to=setTimeout(()=>c.abort(),6000);try{const r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(code)}.json?fields=product_name,brands,nutriments,serving_quantity,ingredients_text`,{signal:c.signal});const j=await r.json();this.status='connected';if(j.status!==1||!j.product)return{found:false};
 const p=j.product,n=p.nutriments||{};return{found:true,name:((p.brands||'').split(',')[0]+' '+(p.product_name||'')).trim()||'Product '+code,barcode:code,per100:{kcal:n['energy-kcal_100g']??(n.energy_100g?n.energy_100g/4.184:0),p:n.proteins_100g,c:n.carbohydrates_100g,f:n.fat_100g,fib:n.fiber_100g,sug:n.sugars_100g,na:(n.sodium_100g??0)*1000},serving:+p.serving_quantity||null,ing:p.ingredients_text||''}}catch(e){this.status='unreachable';return{error:'unreachable'}}finally{clearTimeout(to)}}}};
let cam=null,camLoop=0;
function vScan(){return`<div class="top"><h1>Scan product</h1></div>
 <div class="card"><div id="camBox"><div class="row" style="gap:12px">${art(F('parleg'),56)}<div class="grow sm">Point the camera at a barcode, or photograph the nutrition label. Change the amount you ate and the numbers scale automatically.</div></div></div>
 <div class="grid2" style="margin-top:12px"><button class="btn" data-act="camStart">${ic('scan')} Scan barcode</button><button class="btn hal" data-act="labelPick">${ic('photo')} Photo of label</button></div>
 <input id="labelIn" type="file" accept="image/*" capture="environment" hidden data-ch="labelFile"></div>
 <div class="card"><label class="field" style="margin:0"><span>Or type the barcode number</span></label><div class="row" style="margin-top:6px"><input id="bc" class="inp" inputmode="numeric" placeholder="e.g. 8901058000000" data-in="bc"><button class="btn" data-act="bcGo">Look up</button></div></div>
 <div class="card note info sm"><b>How packaged foods are found</b><br>1. Barcode → product database lookup (Open Food Facts adapter) ${PROVIDERS.off.status==='unreachable'?'— <b>not reachable from this page</b>':PROVIDERS.off.status==='connected'?'— connected':'— tries when you scan'}.<br>2. If not found → photograph the label; AI reads the numbers and you confirm.<br>3. Always available → add by hand. Nothing here is made up: every number is either from a lookup, read from your label, or typed by you.</div>
 ${S.prods.length?`<div class="sec"><h2>Recently scanned</h2><div class="card" style="padding:4px 12px">${S.prods.slice(0,8).map(p=>`<button class="li" data-act="prodOpen" data-b="${p.barcode||''}" data-i="${S.prods.indexOf(p)}">${art({id:'p'+p.name,cat:'pkg',col:'C9A36B'},44)}<div class="grow"><div class="nm ell">${esc(p.name)}</div><div class="sm mut">${p.serving?p.serving+' g serving · ':''}${fmt(p.per100.kcal)} kcal / 100 g</div></div></button>`).join('')}</div></div>`:''}`}
function scanMount(){}
let ZXR=null;
function loadZX(){return window.ZXing?Promise.resolve():new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@zxing/library@0.21.3/umd/index.min.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
async function zxingStart(){const box=$('#camBox');try{await loadZX();const r=new ZXing.BrowserMultiFormatReader();ZXR=r;box.innerHTML='<video class="cam" id="cv" playsinline muted></video><div class="row sp" style="margin-top:8px"><span class="sm mut">Hold steady over the barcode…</span><button class="btn ghost sm" data-act="camStop">Stop</button></div>';r.decodeFromVideoDevice(null,'cv',res=>{if(res){const code=res.getText();scanStop();render();lookupBarcode(code)}})}catch(e){ZXR=null;toast('Live scanning isn’t available in this browser — type the number or photograph the label')}}
function scanStop(){if(ZXR){try{ZXR.reset()}catch(e){}ZXR=null}if(cam){cam.getTracks().forEach(t=>t.stop());cam=null}cancelAnimationFrame(camLoop);camLoop=0}
ACT.camStart=async()=>{const box=$('#camBox');if(!navigator.mediaDevices?.getUserMedia){toast('Camera isn’t available here — type the number or photograph the label');return}if(!('BarcodeDetector' in window))return zxingStart();
 try{const det=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e','code_128']});cam=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});box.innerHTML='<video class="cam" id="cv" playsinline muted></video><div class="row sp" style="margin-top:8px"><span class="sm mut">Hold steady over the barcode…</span><button class="btn ghost sm" data-act="camStop">Stop</button></div>';const v=$('#cv');v.srcObject=cam;await v.play();
  const tick=async()=>{if(!cam)return;try{const r=await det.detect(v);if(r[0]){const code=r[0].rawValue;scanStop();render();return lookupBarcode(code)}}catch(e){}camLoop=requestAnimationFrame(()=>setTimeout(tick,200))};tick()}
 catch(e){scanStop();toast(e.name==='NotAllowedError'?'Camera permission was blocked — type the number or use a label photo':'Couldn’t start the camera')}};
ACT.camStop=()=>{scanStop();render()};
INP.bc=t=>{};ACT.bcGo=()=>{const c=$('#bc').value.replace(/\D/g,'');if(c.length<6)return toast('Enter the full barcode number');lookupBarcode(c)};
async function lookupBarcode(code){const cached=S.prods.find(p=>p.barcode===code);if(cached)return openProduct(cached);openSheet('Looking up '+code,`<div class="empty"><span class="spin"></span><p>Searching product database…</p></div>`,'');
 const r=await PROVIDERS.off.lookup(code);if(r.found){S.prods.unshift(prodRec(r));S.prods=S.prods.slice(0,30);save();return openProduct(S.prods[0])}
 $('#shb').innerHTML=`<div class="card"><div class="b">${r.error?'Barcode database not reachable':'Product not in the database'}</div><p class="sm mut">${r.error?'This page can’t reach an online product database right now (a connected API is needed — the adapter is ready). ':'No record for <b>'+esc(code)+'</b>. '}You can still get exact numbers from the pack:</p><button class="btn hal full" data-act="labelPick2">${ic('photo')} Photograph the nutrition label</button><button class="btn ghost full" style="margin-top:8px" data-act="newFood">Enter values by hand</button></div>`}
const prodRec=r=>({barcode:r.barcode,name:r.name,per100:Object.fromEntries(['kcal','p','c','f','fib','sug','na'].map(k=>[k,num(r.per100[k])])),serving:r.serving,ing:r.ing||''});
ACT.labelPick2=()=>{closeSheet();ACT.labelPick()};
ACT.prodOpen=t=>{const p=S.prods[+t.dataset.i];if(p)openProduct(p)};
function openProduct(p){const g=p.serving||100,n100=Object.assign(zeroN(),p.per100);const units=p.serving?[{l:`serving (${p.serving} g)`,g:p.serving},{l:'g',g:1}]:[{l:'g',g:1}];
 const f={id:'t_'+uid(),name:p.name,alias:'',cat:'pkg',veg:'V',kind:'p',meals:'',n100,mods:[],units,def:p.serving?1:100,col:'C9A36B',src:'label',ing:p.ing,barcode:p.barcode};S.tfoods[f.id]=f;LOG=null;openLog(f,{date:vd})}
ACT.labelPick=()=>{route!=='scan'&&go('scan');setTimeout(()=>$('#labelIn')?.click(),30)};
CHG.labelFile=async t=>{const file=t.files[0];t.value='';if(!file)return;openSheet('Reading label',`<div class="empty"><span class="spin"></span><p>Reading the nutrition label…</p></div>`,'');
 try{const im=await prepImage(file,1600);const r=await aiJson(`This is a photo of a packaged food's nutrition label (Indian/FSSAI style). Read it carefully. Do not guess: use null for anything not printed.\nReply ONLY with JSON: {"product":string|null,"brand":string|null,"servingG":number|null (serving size in g or ml),"basis":"per100"|"perServing" (which column you read the values from; prefer per 100 g/ml),"values":{"kcal":number|null,"p":number|null,"c":number|null,"f":number|null,"fib":number|null,"sug":number|null,"na":number|null (sodium in mg; convert from g if needed)},"ingredients":string|null,"confidence":"high"|"medium"|"low","notes":string}`,{images:im.blob});
  const per100=r.basis==='per100',sg=num(r.servingG)||100,g=per100?100:sg,v=Object.fromEntries(['kcal','p','c','f','fib','sug','na'].map(k=>[k,r.values?.[k]==null?'':r1(num(r.values[k]))]));
  openForm({src:'label',name:[r.brand,r.product].filter(Boolean).join(' ')||'Packaged food',g,v,ing:r.ingredients||'',basis:`Read ${per100?'per 100 g/ml':'per serving'}${r.servingG?`; serving size on pack: ${r.servingG} g`:''}. ${r.notes||''}`,conf:r.confidence});}
 catch(e){$('#shb').innerHTML=`<div class="card"><b>Couldn’t read the label</b><p class="sm mut">${esc(aiMsg(e))}</p><button class="btn full" data-act="newFood">Enter values by hand</button></div>`}};

/* ============ PHOTO AI ============ */
let PH=null;
function vPhoto(){const L=S.learn,nMap=Object.keys(L.map).length,nP=Object.keys(L.portions).length;
 return`<div class="top"><h1>Photo → meal</h1></div>
 <div class="card">${PH&&PH.url?`<img class="prev" src="${PH.url}" alt="Your meal photo">${PH.similar?`<div class="note" style="margin-top:10px"><b>Looks like a meal you logged on ${dlabel(PH.similar.d)}.</b><br><span class="sm">Use the same items? (You can still edit before it’s logged.)</span><div class="row" style="margin-top:8px"><button class="btn hal sm" data-act="phSimilar">Use those items</button><button class="btn ghost sm" data-act="phAnalyze">Analyze photo instead</button></div></div>`:''}
  <label class="field"><span>Anything AI should know? (optional)</span><input class="inp" id="phNote" placeholder="e.g. homemade, dal makhani, 2 rotis"></label>
  <div class="row" style="margin-top:12px"><button class="btn ghost" data-act="phReset">Retake</button><button class="btn grow" data-act="phAnalyze" ${PH.busy?'disabled':''}>${PH.busy?'<span class="spin"></span> Reading your plate…':'Analyze plate'}</button></div>${PH.err?`<div class="note" style="margin-top:10px">${esc(PH.err)}</div>`:''}`
 :`<div class="cap">${art(F('nthali'),84)}<h2 style="margin:8px 0 4px">Snap your thali</h2><p class="sm mut" style="margin:0 0 14px">Thali, home food, restaurant plates, snacks or a single dish. AI guesses the foods and portions — <b>you confirm</b> before anything is logged.</p><div class="grid2"><button class="btn hal" data-act="phCam">${ic('photo')} Take photo</button><button class="btn ghost" data-act="phUp">Upload</button></div></div>`}
  <input id="phCam" type="file" accept="image/*" capture="environment" hidden data-ch="phFile"><input id="phUp" type="file" accept="image/*" hidden data-ch="phFile"></div>
 <button class="btn ghost full" style="margin-top:10px" data-act="plManual">${ic('bowl')} Build a meal by hand instead</button>
 <div class="sec"><h2>What Bitewise has learned about you</h2><div class="card sm">${nMap||nP||L.hashes.length?`<p style="margin:0 0 8px">Corrections you made are remembered and sent with your next photos so repeat meals need fewer fixes.</p>
  ${Object.entries(L.map).filter(([,v])=>F(v.to)).slice(0,8).map(([k,v])=>`<div class="row sp li"><span>“${esc(k)}” → <b>${esc(F(v.to).name)}</b> <span class="mut">(${v.n}×)</span></span><button class="iconbtn" style="width:32px;height:32px" data-act="unlearn" data-k="${esc(k)}" aria-label="Forget">${ic('x',14)}</button></div>`).join('')}
  <div class="mut" style="margin-top:8px">${nP} usual portion${nP===1?'':'s'} learned · ${L.hashes.length} usual meal${L.hashes.length===1?'':'s'} remembered</div>${L.hashes.length?`<div class="row" style="margin-top:8px;flex-wrap:wrap">${L.hashes.slice(0,8).map(h=>`<img src="${h.th}" alt="" width="44" height="44" style="border-radius:10px">`).join('')}</div>`:''}<button class="btn bad sm" style="margin-top:10px" data-act="learnClear">Forget everything learned</button>`:'After a few photo meals with corrections (“that’s dal makhani, not dal”, “this bowl is ~150 g”), repeat meals will get easier.'}</div></div>`}
ACT.phCam=()=>$('#phCam').click();ACT.phUp=()=>$('#phUp').click();ACT.phReset=()=>{PH=null;render()};
ACT.unlearn=t=>{delete S.learn.map[t.dataset.k];save();render()};ACT.learnClear=()=>{if(confirm('Forget all learned corrections, portions and remembered meals?')){S.learn={map:{},portions:{},hashes:[]};save();render()}};
CHG.phFile=async t=>{const file=t.files[0];t.value='';if(!file)return;PH={busy:false};try{const im=await prepImage(file);PH=Object.assign({busy:false},im);let best=null;for(const h of S.learn.hashes){const d=ham(h.h,im.hash);if(d<=9&&(!best||d<best.d))best={...h,dist:d}}PH.similar=best;render()}catch(e){PH={err:'Couldn’t open that image. Try another photo.'};render()}};
ACT.phSimilar=()=>{const s=PH.similar;openPlate({title:'Your usual meal',ai:true,items:s.items.map(i=>({...i,mods:{...i.mods}})),photo:PH.url,hash:PH.hash,thumb:PH.thumb,note:'Matched to a meal you logged before.'})};
ACT.phAnalyze=async()=>{if(!PH||!PH.blob||PH.busy)return;const note=($('#phNote')?.value||'').trim();PH.busy=true;PH.err='';render();
 try{const sm=await ai();if(!sm)throw{message:AIERR||'AI is not available in this view.'};const caps=await sm.limits().catch(()=>null);if(caps&&!caps.images)throw{code:'images_unavailable'};
  const sim=PH.similar?`A very similar earlier meal from this user contained: ${PH.similar.items.map(i=>F(i.fid)?.name+' ('+r0(calc(F(i.fid),i.qty,i.unit,i.mods).g)+' g)').join(', ')}. Use it as a strong hint.\n`:'';
  const r=await sm.json(`You are Bitewise's food-photo analyst for Indian meals. The photo shows a meal (thali, home-cooked food, restaurant food, snacks or drinks).\n1. Identify each distinct food or drink you can see.\n2. Estimate the served weight of each in grams (ml for liquids), using plate/katori/roti size as scale.\n3. Match each item to the database below when a reasonable match exists (be specific: e.g. dal makhani is dark and creamy, dal tadka is yellow and thin). Otherwise set dbId to null and give per-100 g estimates.\nBe honest about uncertainty: set confidence "low" when unsure.\nReply ONLY with JSON: {"items":[{"name":string,"dbId":string|null,"grams":number,"confidence":"high"|"medium"|"low","note":string,"per100":{"kcal":number,"p":number,"c":number,"f":number,"fib":number,"sug":number,"na":number}}],"caveat":string}. Include per100 only when dbId is null.\n${note?'User note: '+note+'\n':''}${learnPrompt()}${sim}Database (id=name): ${dbIdList()}`,{images:PH.blob});
  const items=(r.items||[]).slice(0,14).map(aiItemToPlate);if(!items.length)throw{message:'I couldn’t spot any food in that photo. Try a closer, well-lit shot — or build the meal by hand.'};
  PH.busy=false;const p=PH;save();openPlate({title:'Is this correct?',ai:true,items,photo:p.url,hash:p.hash,thumb:p.thumb,note:r.caveat})}
 catch(e){PH.busy=false;PH.err=aiMsg(e);render()}};
ACT.plManual=()=>{PL=null;openPlate({title:'Build a meal',items:[]});setTimeout(()=>ACT.plAdd(),0)};

/* ============ VOICE / TYPE-IT LOGGING ============ */
const speechAvail=()=>window.SpeechRecognition||window.webkitSpeechRecognition||(window.Capacitor&&window.Capacitor.Plugins&&window.Capacitor.Plugins.SpeechRecognition);
let REC=null,VS={text:'',live:false,err:''};
function stopVoice(){if(REC){try{REC.stop()}catch(e){}REC=null}VS.live=false}
ACT.voice=()=>{VS={text:'',live:false,err:''};openSheet('Say what you ate','','');renderVoice();if(speechAvail())setTimeout(startVoice,150)};
function renderVoice(){const SR=speechAvail();$('#shb').innerHTML=`<div class="c" style="padding:8px 0"><button class="micbtn ${VS.live?'live':''}" style="width:84px;height:84px;border-radius:50%;margin:0 auto" data-act="${VS.live?'vStop':'vStart'}" aria-label="${VS.live?'Stop listening':'Start listening'}">${ic('mic',36)}</button><p class="sm mut" style="margin:10px 0 0">${SR?(VS.live?'Listening… speak naturally':'Tap the mic and speak'):'Voice input isn’t supported in this browser — type it instead'}</p></div>
 ${SR?`<div class="opts" style="justify-content:center;margin:6px 0"><button class="opt ${S.ui.voiceLang==='en-IN'?'on':''}" data-act="vLang" data-l="en-IN">English</button><button class="opt ${S.ui.voiceLang==='hi-IN'?'on':''}" data-act="vLang" data-l="hi-IN">हिन्दी / Hinglish</button></div>`:''}
 ${VS.err?`<div class="note sm">${esc(VS.err)}</div>`:''}<label class="field"><span>What you said (edit if needed)</span><textarea class="inp" id="vt" data-in="vt" placeholder="“I had 2 rotis, dal makhani and a cup of chai”">${esc(VS.text)}</textarea></label>
 <p class="xs mut">Try: “2 eggs and toast with butter”, “ek katori rajma chawal”, “1 glass chaas”. You’ll review everything before it’s logged.</p>`;
 $('#shf')?.remove();$('.sheet').insertAdjacentHTML('beforeend',`<div class="sh-f" id="shf"><button class="btn full" data-act="vGo">Find these foods</button></div>`)}
INP.vt=t=>{VS.text=t.value};ACT.vLang=t=>{S.ui.voiceLang=t.dataset.l;save();stopVoice();renderVoice()};ACT.vStop=()=>{stopVoice();renderVoice()};ACT.vStart=()=>startVoice();
async function startNativeVoice(P){try{const av=await P.available();if(!av.available)throw{n:'na'};const pm=await P.requestPermissions();if(pm.speechRecognition&&pm.speechRecognition!=='granted')throw{n:'denied'};VS.err='';VS.live=true;renderVoice();REC={stop:()=>P.stop()};P.addListener('partialResults',d=>{VS.text=(d.matches||[])[0]||'';const ta=$('#vt');if(ta)ta.value=VS.text});await P.start({language:S.ui.voiceLang,maxResults:1,partialResults:true,popup:false});VS.live=false;REC=null;renderVoice();if(VS.text.trim())ACT.vGo()}catch(e){VS.live=false;REC=null;VS.err=e&&e.n==='denied'?'Microphone or speech permission was denied. Enable it in Settings, or type instead.':'Voice input isn’t available on this device. Type instead.';renderVoice()}}
function startVoice(){const NP=window.Capacitor&&window.Capacitor.Plugins&&window.Capacitor.Plugins.SpeechRecognition;if(NP&&$('#vt'))return startNativeVoice(NP);const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR||!$('#vt'))return;stopVoice();try{const r=new SR();REC=r;r.lang=S.ui.voiceLang;r.interimResults=true;r.continuous=false;VS.err='';
 r.onresult=e=>{VS.text=[...e.results].map(x=>x[0].transcript).join(' ');const ta=$('#vt');if(ta)ta.value=VS.text};
 r.onerror=e=>{VS.live=false;VS.err=e.error==='not-allowed'||e.error==='service-not-allowed'?'Microphone access is blocked here. Type what you ate instead, or allow the mic in your browser.':e.error==='no-speech'?'Didn’t catch anything — tap the mic and try again.':'Voice input stopped ('+e.error+'). You can type instead.';renderVoice()};
 r.onend=()=>{VS.live=false;if(REC===r){REC=null;const ta=$('#vt');const keep=ta?ta.value:VS.text;VS.text=keep;renderVoice();if(VS.text.trim()&&!VS.err)ACT.vGo()}};VS.live=true;r.start();renderVoice()}catch(e){VS.live=false;VS.err='Couldn’t start voice input. Type instead.';renderVoice()}}
ACT.vGo=async()=>{const text=($('#vt')?.value||VS.text).trim();if(!text)return toast('Say or type what you ate first');stopVoice();let items=parseSpeech(text),miss=items.filter(i=>!i.fid).map(i=>i.text),note=null;
 if(miss.length&&canAI()){$('#shb').innerHTML=`<div class="empty"><span class="spin"></span><p>Understanding “${esc(text)}”…</p></div>`;$('#shf')?.remove();
  try{const r=await aiJson(`Parse this food-log sentence (English, Hindi or Hinglish) into separate foods for an Indian calorie tracker: "${text.replace(/"/g,"'")}".\nMatch each to the database below when reasonable, else dbId null with per-100 g estimates. qty is the number of units the person had; unit is the unit word said (roti, katori, cup, glass, piece, slice, plate, tsp, tbsp, g, ml) or null; grams only if a weight was said or you must estimate.\nReply ONLY with JSON: {"items":[{"name":string,"dbId":string|null,"qty":number,"unit":string|null,"grams":number|null,"per100":{"kcal":number,"p":number,"c":number,"f":number,"fib":number,"sug":number,"na":number}}]}\nDatabase (id=name): ${dbIdList()}`,{modelTier:'quick'});
   const out=(r.items||[]).map(it=>{const f=it.dbId&&F(it.dbId);if(f){const uw=it.unit?String(it.unit).toLowerCase():null,ul=pickUnit(f,uw),u=unitOf(f,ul);const q=it.grams&&(!uw||ul==='g'||ul==='ml')?(u.l==='g'||u.l==='ml'?Math.round(it.grams/5)*5:qtyFor(f,it.grams)):(num(it.qty)||f.def);return{fid:f.id,qty:q,unit:ul,mods:defMods(f,q*u.g),ai:{name:it.name,dbId:f.id,grams:q*u.g,conf:'medium'}}}
    return aiItemToPlate({...it,grams:it.grams||100})});if(out.length){openPlate({title:'Here’s what I heard',ai:true,items:out,note:'“'+text.slice(0,90)+'” — check the amounts; AI matched your words to foods.'});return}}
  catch(e){note=aiMsg(e)}}
 const ok=items.filter(i=>i.fid).map(i=>{const f=F(i.fid);return{fid:f.id,qty:i.qty,unit:i.unit,mods:defMods(f,i.qty*unitOf(f,i.unit).g)}});
 if(!ok.length){VS.err='I couldn’t match any foods'+(note?' ('+note+')':'')+'. Try simpler words like “2 roti” or search by name.';renderVoice();return}
 openPlate({title:'Here’s what I heard',items:ok,note:'“'+text.slice(0,90)+'”'+(miss.length?' — couldn’t find: '+miss.join(', ')+'. Use “Add missing food”.':'')});if(miss.length)PL.ai=false};
