'use strict';
/* ============ HISTORY ============ */
const MCOL={kcal:'var(--cal)',p:'var(--pro)',c:'var(--carb)',f:'var(--fat)',fib:'var(--fib)'},MLAB={kcal:'Calories',p:'Protein',c:'Carbs',f:'Fat',fib:'Fibre'},MU={kcal:'kcal',p:'g',c:'g',f:'g',fib:'g'};
const monthDays=hm=>{const[y,m]=hm.split('-').map(Number),n=new Date(y,m,0).getDate();return Array.from({length:n},(_,i)=>hm+'-'+pad(i+1))};
const mondayOf=d=>{const x=pd(d),w=(x.getDay()+6)%7;return addDays(d,-w)};
function vHistory(){const seg=UI.hseg;return`<div class="top"><h1>History</h1></div><div class="seg" style="margin-bottom:12px"><button class="${seg==='month'?'on':''}" data-act="hseg" data-s="month">Month</button><button class="${seg==='search'?'on':''}" data-act="hseg" data-s="search">Food history</button></div>${seg==='month'?histMonth():histSearch()}`}
function histMonth(){const hm=UI.hm,days=monthDays(hm),t=today(),M=UI.hmetric,[y,m]=hm.split('-').map(Number);
 const vals=days.map(d=>d>t?0:dayN(d)[M]),logged=days.filter(d=>d<=t&&entriesOn(d).length),lv=logged.map(d=>dayN(d)[M]),tgt=S.tg[M];
 const avgV=avg(lv),hiD=logged.reduce((a,b)=>dayN(b)[M]>dayN(a)[M]?b:a,logged[0]),loD=logged.reduce((a,b)=>dayN(b)[M]<dayN(a)[M]?b:a,logged[0]);
 const onK=logged.filter(d=>Math.abs(dayN(d).kcal-budgetFor(d))<=budgetFor(d)*.1).length,pOk=logged.filter(d=>dayN(d).p>=S.tg.p*.9).length;
 const wk={};days.filter(d=>d<=t&&entriesOn(d).length).forEach(d=>{(wk[mondayOf(d)]||(wk[mondayOf(d)]=[])).push(dayN(d))});
 const mx=Math.max(...vals,1);
 return`<div class="row sp" style="margin-bottom:10px"><button class="iconbtn" data-act="hm" data-d="-1" aria-label="Previous month">${ic('left')}</button><h2>${MON[m-1]} ${y}</h2><button class="iconbtn" data-act="hm" data-d="1" aria-label="Next month" ${hm>=t.slice(0,7)?'disabled style="opacity:.3"':''}>${ic('right')}</button></div>
 <div class="chips">${Object.keys(MLAB).map(k=>`<button class="chip ${M===k?'on':''}" data-act="hmet" data-k="${k}">${MLAB[k]}</button>`).join('')}</div>
 <div class="card"><div class="row sp xs mut" style="margin-bottom:6px"><span>Each bar is one day · tap for the full log</span><span style="color:var(--pro)">- - target ${fmt(tgt)}</span></div>${barsSVG(vals,{labels:days.map((d,i)=>(i===0||(i+1)%5===0)?i+1:''),target:tgt,color:MCOL[M],keys:days})}</div>
 <div class="grid2" style="margin-top:12px"><div class="stat"><span>Average ${MLAB[M].toLowerCase()} / day</span><b class="num">${fmt(avgV)} <small class="sm mut">${MU[M]}</small></b></div><div class="stat"><span>Days logged</span><b class="num">${logged.length}</b></div>
 <div class="stat"><span>Days on calorie target (±10%)</span><b class="num">${onK}<small class="sm mut"> / ${logged.length}</small></b></div><div class="stat"><span>Protein target hit (≥90%)</span><b class="num" style="color:var(--pro)">${pOk}<small class="sm mut"> / ${logged.length}</small></b></div>
 <div class="stat"><span>Highest day</span><b class="num">${hiD?fmt(dayN(hiD)[M]):'—'}</b><span>${hiD?dlabel(hiD):''}</span></div><div class="stat"><span>Lowest day</span><b class="num">${loD?fmt(dayN(loD)[M]):'—'}</b><span>${loD?dlabel(loD):''}</span></div></div>
 ${Object.keys(wk).length?`<div class="sec"><h2>Weekly averages</h2><div class="card" style="padding:4px 12px">${Object.entries(wk).map(([s,a])=>{const e=addDays(s,6);return`<div class="li"><div class="grow"><div class="nm">${pd(s).getDate()} ${MON[pd(s).getMonth()]} – ${pd(e).getDate()} ${MON[pd(e).getMonth()]}</div><div class="sm mut">${a.length} day${a.length>1?'s':''} logged</div></div><div class="k">${fmt(avg(a.map(x=>x[M])))}<small style="color:var(--mut)">${MU[M]} / day</small></div></div>`}).join('')}</div></div>`:''}
 <div class="sec"><h2>Day by day</h2><div class="card" style="padding:6px 12px">${days.filter(d=>d<=t).reverse().map(d=>{const v=dayN(d)[M],has=entriesOn(d).length;return`<button class="dayrow" data-act="openDay" data-d="${d}"><span class="mut">${pd(d).getDate()} ${MON[pd(d).getMonth()]}</span><div class="pbar"><i style="width:${has?Math.min(100,v/mx*100):0}%;background:${MCOL[M]}"></i></div><b>${has?fmt(v):'—'}</b></button>`}).join('')}</div></div>`}
function histSearch(){const q=norm(UI.hq),hits=q?S.entries.filter(e=>norm(e.name).includes(q)):[],days=[...new Set(hits.map(e=>e.date))].sort().reverse();
 return`<div class="search">${ic('search')}<input type="search" placeholder="Search everything you’ve eaten — e.g. paneer" value="${esc(UI.hq)}" data-in="hq" aria-label="Search food history"></div>${q?`<p class="sm mut" style="margin:10px 2px">${hits.length?`You logged “${esc(UI.hq)}” on <b>${days.length} day${days.length>1?'s':''}</b> (${hits.length} entries).`:'Nothing logged with that name yet.'}</p><div class="card" style="padding:4px 12px">${days.slice(0,60).map(d=>hits.filter(e=>e.date===d).map((e,i)=>`<button class="li" data-act="openDay" data-d="${d}">${art(F(e.fid),40)}<div class="grow"><div class="nm ell">${esc(e.name)}</div><div class="sm mut">${dlabel(d)} · ${t12(e.time)} · ${MEALNAME[e.meal]||e.cust}</div></div><div class="k">${fmt(e.n.kcal)}<small>${r0(e.n.p)} g P</small></div></button>`).join('')).join('')}</div>`:`<div class="card empty" style="margin-top:12px">${art(F('paneer'),56)}<br>Type a food to see every day you ate it.</div>`}`}
INP.hq=t=>{UI.hq=t.value;const pos=t.selectionStart;render();const i=$('input[data-in=hq]');i.focus();i.setSelectionRange(pos,pos)};
ACT.hseg=t=>{UI.hseg=t.dataset.s;render()};ACT.hmet=t=>{UI.hmetric=t.dataset.k;render()};
ACT.hm=t=>{const[y,m]=UI.hm.split('-').map(Number),d=new Date(y,m-1+ +t.dataset.d,1);UI.hm=d.getFullYear()+'-'+pad(d.getMonth()+1);render()};
ACT.openDay=t=>{const d=t.dataset.d,es=entriesOn(d),n=dayN(d),gm=groupMeals(es),al=allowance(d);
 openSheet(dlabel(d),`<div class="card"><div class="row sp"><div><span class="num" style="font-size:38px">${fmt(n.kcal)}</span><span class="mut"> / ${fmt(al)} kcal</span></div><div style="text-align:right"><span class="num" style="font-size:30px;color:var(--pro)">${r0(n.p)}</span><span class="mut"> g protein</span></div></div><div class="pbar" style="margin:8px 0"><i style="width:${Math.min(100,n.kcal/al*100)}%;background:${n.kcal>al?'var(--bad)':'var(--cal)'}"></i></div><div class="mac"><span>Carbs <b>${r0(n.c)} g</b></span><span>Fat <b>${r0(n.f)} g</b></span><span>Fibre <b>${r0(n.fib)} g</b></span><span>Sugar <b>${r0(n.sug)} g</b></span></div></div>
 ${gm.length?gm.map(g=>`<div class="sec" style="margin-top:14px"><h3 class="row sp"><span>${esc(g.name)}</span><span class="mut sm" style="font-family:var(--fb)">${fmt(g.n.kcal)} kcal · ${r0(g.n.p)} g P</span></h3><div class="card" style="padding:4px 12px;margin-top:6px">${g.es.map(e=>`<button class="li" data-act="editEntry" data-id="${e.id}">${art(F(e.fid),40)}<div class="grow"><div class="nm ell">${esc(e.name)}</div><div class="sm mut">${esc(qtxt(F(e.fid),e.qty,e.unit))} · ${t12(e.time)}</div></div><div class="k">${fmt(e.n.kcal)}<small>${r0(e.n.p)} g P</small></div></button>`).join('')}</div></div>`).join(''):'<div class="card empty">Nothing logged this day.</div>'}`,
 `<button class="btn ghost" data-act="dayGo" data-d="${d}">Open on Home</button><button class="btn" data-act="dayAdd" data-d="${d}">＋ Add food</button>`)};
ACT.dayGo=t=>{vd=t.dataset.d;go('home')};ACT.dayAdd=t=>{vd=t.dataset.d;UI.q='';go('add')};

/* ============ INSIGHTS ============ */
function vInsights(){const s=UI.insSeg;return`<div class="top"><h1>Insights</h1></div><div class="seg" style="margin-bottom:12px">${[['week','Week'],['timing','Timing'],['protein','Protein'],['ideas','Ideas']].map(([k,l])=>`<button class="${s===k?'on':''}" data-act="iseg" data-s="${k}">${l}</button>`).join('')}</div>${({week:insWeek,timing:insTiming,protein:insProtein,ideas:insIdeas})[s]()}<p class="xs mut c" style="margin-top:16px">Patterns from your own log — not medical advice or a diagnosis.</p>`}
ACT.iseg=t=>{UI.insSeg=t.dataset.s;render()};
function insWeek(){const L=insightLines(),end=today(),{rows}=weekStats(end);if(!L.length)return`<div class="card empty">${art(F('nthali'),64)}<br><b>Log a few days to see your weekly summary.</b></div>`;
 return`<div class="card"><h3 style="margin-bottom:8px">Your week</h3>${L.map(l=>`<p style="margin:0 0 8px">• ${esc(l)}</p>`).join('')}</div><div class="sec"><h2>Calories, last 7 days</h2><div class="card">${barsSVG(rows.map(r=>r.n.kcal),{labels:rows.map(r=>DOW[pd(r.d).getDay()][0]),target:S.tg.kcal,color:'var(--cal)',keys:rows.map(r=>r.d),h:170})}</div></div>
 <div class="sec"><h2>Protein, last 7 days</h2><div class="card">${barsSVG(rows.map(r=>r.n.p),{labels:rows.map(r=>DOW[pd(r.d).getDay()][0]),target:S.tg.p,color:'var(--pro)',keys:rows.map(r=>r.d),h:170})}</div></div>
 <div class="grid2" style="margin-top:12px"><div class="stat"><span>Logging streak</span><b class="num">${streak()} <small class="sm mut">days</small></b></div><div class="stat"><span>Exercise this week</span><b class="num">${fmt(rows.reduce((a,r)=>a+exKcal(r.d),0))} <small class="sm mut">kcal</small></b></div></div>`}
function insTiming(){const T=timingStats(30);if(!T.days)return`<div class="card empty">${art(F('tea'),56)}<br><b>Meal timing appears once you’ve logged a few days.</b></div>`;
 const tm=k=>T.avgT[k]?t12(T.avgT[k]):'—';
 return`<div class="grid3"><div class="stat"><span>Breakfast</span><b class="num" style="font-size:19px">${tm('breakfast')}</b></div><div class="stat"><span>Lunch</span><b class="num" style="font-size:19px">${tm('lunch')}</b></div><div class="stat"><span>Dinner</span><b class="num" style="font-size:19px">${tm('dinner')}</b></div></div>
 <div class="sec"><h2>When your calories land <small>avg kcal per hour</small></h2><div class="card">${hoursSVG(T.hrs)}<p class="xs mut" style="margin:6px 0 0"><span style="color:var(--bad)">■</span> after 8 PM</p></div></div>
 <div class="grid2" style="margin-top:12px"><div class="stat"><span>Calories after 8 PM</span><b class="num">${fmt(T.after8)}</b><span>kcal/day · ${Math.round(T.share8*100)}% of intake</span></div><div class="stat"><span>Late-night eating</span><b class="num">${T.late}</b><span>of ${T.days} logged days (after 10 PM)</span></div>
 <div class="stat" style="grid-column:1/-1"><span>Most common snacking time</span><b class="num">${T.snackHour==null?'—':t12(pad(T.snackHour)+':00')+' hour'}</b></div></div><p class="sm mut">Based on the last 30 days you logged (${T.days} days). Average meal time uses your first entry of each meal.</p>`}
function insProtein(){const t=dayN(today()),tg=S.tg.p,rem=Math.max(0,tg-t.p),src=proteinSources(7),{rows}=weekStats(today());
 return`<div class="card c"><div class="mut sm b" style="letter-spacing:.06em;text-transform:uppercase">Protein today</div><div class="num" style="font-size:64px;color:var(--pro);line-height:1">${r0(t.p)}<small style="font-size:.35em" class="mut"> / ${tg} g</small></div><div class="pbar" style="margin:10px 0"><i style="width:${Math.min(100,t.p/tg*100)}%;background:var(--pro)"></i></div><div class="sm">${rem>0?`<b>${r0(rem)} g</b> to go`:'Target reached 🎉'}</div></div>
 <div class="sec"><h2>Last 7 days</h2><div class="card">${barsSVG(rows.map(r=>r.n.p),{labels:rows.map(r=>DOW[pd(r.d).getDay()][0]),target:tg,color:'var(--pro)',keys:rows.map(r=>r.d),h:160})}</div></div>
 <div class="sec"><h2>Best protein sources <small>last 7 days</small></h2><div class="card" style="padding:4px 12px">${src.length?src.map(([n,p],i)=>`<div class="li"><span class="num mut" style="width:20px">${i+1}</span><div class="grow"><div class="nm ell">${esc(n)}</div><div class="pbar" style="margin-top:6px"><i style="width:${p/src[0][1]*100}%;background:var(--pro)"></i></div></div><div class="k">${r0(p)} g</div></div>`).join(''):'<div class="empty sm">Log some meals to see your top sources.</div>'}</div></div>
 ${rem>0?`<button class="btn full" style="margin-top:12px" data-act="iseg" data-s="ideas">Ideas to close the gap</button>`:''}`}
function insIdeas(){const n=dayN(today()),al=allowance(today()),remK=al-n.kcal,remP=Math.max(0,S.tg.p-n.p),sg=suggest(remK,remP);
 return`<div class="card c"><div class="mut sm b" style="letter-spacing:.06em;text-transform:uppercase">Remaining today</div><div class="row" style="justify-content:center;gap:24px;margin-top:6px"><div><span class="num" style="font-size:38px">${fmt(Math.max(0,remK))}</span><br><span class="mut sm">kcal</span></div><div><span class="num" style="font-size:38px;color:var(--pro)">${r0(remP)}</span><br><span class="mut sm">g protein</span></div></div></div>
 ${sg.length?sg.map((c,i)=>`<div class="card"><div class="row"><div class="grow"><div class="b">${esc(c[0]||c.name)}</div><div class="sm mut">${c.items.map(([id,g])=>FOOD[id].name.split(' (')[0].split(' / ')[0]+' '+r0(g)+'g').join(' · ')}</div><div class="sm" style="margin-top:4px"><b>${fmt(c.n.kcal)}</b> kcal · <b style="color:var(--pro)">${r0(c.n.p)} g</b> protein</div></div><button class="btn sm" data-act="sugAdd" data-i="${i}">＋ Plate</button></div></div>`).join(''):`<div class="card empty">${remK<60?'You’re at your calorie budget for today — nothing more needed.':'No matching ideas for your diet preference.'}</div>`}
 <p class="xs mut c">Suggestions are simple Indian combinations that fit what’s left of your budget and your diet setting (${{veg:'vegetarian',egg:'eggetarian',nv:'non-veg'}[S.me?.diet||'nv']}). Amounts are approximate.</p>`}
ACT.sugAdd=t=>{const n=dayN(today()),sg=suggest(allowance(today())-n.kcal,Math.max(0,S.tg.p-n.p))[+t.dataset.i];if(!sg)return;openPlate({title:sg.name,items:sg.items.map(([id,g])=>{const f=FOOD[id],q=qtyFor(f,g);return{fid:id,qty:q,unit:f.units[0].l,mods:defMods(f,q*f.units[0].g)}})})};

/* ============ PROFILE ============ */
const GOALS={lose:'Lose weight',maintain:'Maintain weight',gain:'Gain weight',muscle:'Build muscle'},ACTL={s:['Mostly sitting','desk job, little walking'],l:['Lightly active','on your feet a bit, some walking'],m:['Moderately active','regular exercise or active job'],v:['Very active','hard training or physical work']};
const chipSet=(k,opts,cur)=>`<div class="opts">${opts.map(([v,l])=>`<button class="opt ${String(cur)===String(v)?'on':''}" data-act="meSet" data-k="${k}" data-v="${v}">${l}</button>`).join('')}</div>`;
function vProfile(){const me=S.me||{},tg=S.tg,wk=planWeeks(me),ws=[...S.weights].sort((a,b)=>a.d.localeCompare(b.d)),cur=ws.length?ws[ws.length-1].kg:me.wt,sw=me.sw||ws[0]?.kg,prog=me.tw&&sw&&sw!==me.tw?Math.max(0,Math.min(1,(sw-cur)/(sw-me.tw))):null;
 const num_=(k,l,u,st='any')=>`<label class="field" style="margin:0"><span>${l}</span><input class="inp" type="number" inputmode="decimal" step="${st}" value="${me[k]??''}" data-ch="me" data-k="${k}" ${u?`placeholder="${u}"`:''}></label>`;
 const tin=(k,l)=>`<label class="field" style="margin:0"><span>${l}</span><input class="inp" type="number" inputmode="decimal" value="${tg[k]}" data-ch="tg" data-k="${k}"></label>`;
 const tog=(k,l,d)=>`<label class="row li" style="cursor:pointer"><span class="grow"><b>${l}</b><br><span class="sm mut">${d}</span></span><input type="checkbox" ${S.ui[k]?'checked':''} data-ch="ui" data-k="${k}" style="width:24px;height:24px"></label>`;
 return`<div class="top"><h1>Profile</h1></div>
 <div class="card"><div class="row">${art(F('nthali'),56)}<div class="grow"><div class="b" style="font:700 20px var(--fd)">${esc(me.name||'You')}</div><div class="sm mut">${GOALS[me.goal]||'Set your goal'}${me.tw&&me.goal!=='maintain'?` · target ${me.tw} kg`:''}</div></div></div>${prog!=null?`<div style="margin-top:12px"><div class="row sp sm"><span>${r1(sw)} kg → ${me.tw} kg</span><b>${Math.round(prog*100)}%</b></div><div class="pbar" style="margin-top:6px"><i style="width:${prog*100}%;background:var(--fib)"></i></div>${wk?`<div class="xs mut" style="margin-top:6px">At ${me.pace} kg/week the plan is about ${wk} weeks.</div>`:''}</div>`:''}</div>
 <div class="sec"><h2>Daily targets</h2><div class="card"><div class="grid2">${tin('kcal','Calories (kcal)')}${tin('p','Protein (g)')}${tin('c','Carbs (g)')}${tin('f','Fat (g)')}${tin('fib','Fibre (g)')}${tin('water','Water (ml)')}</div>
  <p class="xs mut" style="margin:10px 0">These are <b>estimates</b> (Mifflin-St Jeor formula, your activity and goal) — not medical advice. Change any number to suit you or your doctor/dietitian’s advice.</p><button class="btn ghost full" data-act="recalc">Recalculate from my body stats</button></div></div>
 <div class="sec"><h2>Weekly rhythm</h2><div class="card"><label class="row" style="cursor:pointer"><span class="grow"><b>Plan more for weekends</b><br><span class="sm mut">Same weekly average, shifted: extra on Sat &amp; Sun, a little less Mon–Fri.</span></span><input type="checkbox" ${S.sched.on?'checked':''} data-ch="sched" style="width:24px;height:24px"></label>${S.sched.on?`<label class="field"><span>Extra kcal on weekends</span><input class="inp" type="number" inputmode="numeric" value="${S.sched.extra}" data-ch="schedX"></label><p class="xs mut" style="margin:8px 0 0">Mon–Fri ${fmt(tg.kcal-Math.round(S.sched.extra*2/5))} · Sat–Sun ${fmt(tg.kcal+S.sched.extra)} kcal</p>`:''}</div></div>
 <div class="sec"><h2>About you</h2><div class="card"><div class="grid2">${num_('age','Age')}${num_('ht','Height (cm)')}${num_('wt','Weight (kg)')}${num_('tw','Target weight (kg)')}</div>
  <div class="field"><span>Sex (for the calorie formula)</span>${chipSet('sex',[['f','Female'],['m','Male'],['o','Other']],me.sex)}</div><div class="field"><span>Goal</span>${chipSet('goal',Object.entries(GOALS),me.goal)}</div>
  ${me.goal==='lose'||me.goal==='gain'?`<div class="field"><span>Pace (kg per week)</span>${chipSet('pace',[[.25,'0.25 easy'],[.5,'0.5 steady'],[.75,'0.75 fast']],me.pace)}</div>`:''}<div class="field"><span>Activity</span>${chipSet('act',Object.entries(ACTL).map(([k,v])=>[k,v[0]]),me.act)}</div>
  <div class="field"><span>Diet</span>${chipSet('diet',[['veg','Vegetarian'],['egg','Eggetarian'],['nv','Non-veg']],me.diet)}</div>
  <div class="field"><span>Avoid / allergies</span><div class="opts">${[['gluten','Gluten'],['lactose','Lactose'],['nuts','Nuts'],['jain','Onion-garlic free']].map(([v,l])=>`<button class="opt ${(me.allergy||[]).includes(v)?'on':''}" data-act="meTog" data-k="allergy" data-v="${v}">${l}</button>`).join('')}</div></div>
  <label class="field"><span>Name</span><input class="inp" value="${esc(me.name||'')}" data-ch="me" data-k="name"></label></div></div>
 ${S.ui.weight?weightCard(ws,cur):''}
 <div class="sec"><h2>Settings</h2><div class="card" style="padding:4px 12px">${tog('water','Water tracker','Glasses and ml on Home')}${tog('weight','Weight tracker','Weight, waist and body-fat log')}${tog('fast','Fasting timer','Simple intermittent-fasting clock on Home')}${tog('exAdd','Add exercise to my budget','Burned calories raise the day’s allowance')}
  <div class="li"><span class="grow b">Theme</span><div class="seg" style="width:200px">${['auto','light','dark'].map(t=>`<button class="${S.ui.theme===t?'on':''}" data-act="themeSet" data-t="${t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div></div>${S.ui.fast?`<div class="li"><span class="grow b">Fasting plan</span>${chipSet('fastPlan',[['12:12','12:12'],['14:10','14:10'],['16:8','16:8'],['18:6','18:6']],S.fast.plan)}</div>`:''}</div></div>
 ${CFG?`<div class="sec"><h2>Permissions & app</h2><div class="card" style="padding:4px 12px">${permCard()}${isStandalone()?'':`<div class="li"><div class="grow"><b>Install app</b><br><span class="xs mut">${DEFERRED?'One-tap logging from your home screen.':isIOS()?'Tap Share, then “Add to Home Screen”.':'Use your browser menu → Install app.'}</span></div>${DEFERRED?'<button class="btn sm" data-act="install">Install</button>':''}</div>`}</div></div>`:''}
 <div class="sec"><h2>Data & connections</h2><div class="card sm"><p style="margin:0 0 8px">Your log is stored in this browser only (private to you; clearing site data erases it).</p>
  ${dataRows().map(([a,b,c])=>`<div class="li"><span class="badge ${c}">${c==='ok'?'ready':c==='ai'?'AI':'setup'}</span><div class="grow"><b>${a}</b><br><span class="xs mut">${b}</span></div></div>`).join('')}
  ${CFG?`<div class="row wrap" style="margin-top:10px"><button class="btn ghost sm" data-act="exportJson">Download backup</button><button class="btn ghost sm" data-act="exportCsv">Export CSV</button><button class="btn ghost sm" data-act="importPick">Restore backup</button><input id="impIn" type="file" accept=".json,application/json" hidden data-ch="importJson"></div>`:''}<a class="xs mut" href="/privacy.html" target="_blank" rel="noopener" style="display:block;margin-top:10px">Privacy notice</a><button class="btn bad full" style="margin-top:10px" data-act="resetAll">Erase all my data</button></div></div>`}
function weightCard(ws,cur){const pts=ws.map(w=>({x:pd(w.d).getTime()/864e5,y:w.kg,l:pd(w.d).getDate()+' '+MON[pd(w.d).getMonth()]}));
 return`<div class="sec"><h2>Weight <small>optional</small></h2><div class="card">${pts.length>1?lineSVG(pts):`<p class="sm mut" style="margin:0 0 8px">${pts.length?'Add another weigh-in to see your graph.':'Log your weight now and then to see a graph.'}</p>`}
 <div class="grid3" style="margin-top:10px"><label class="field" style="margin:0"><span>Weight (kg)</span><input class="inp" id="wkg" type="number" inputmode="decimal" step="0.1" placeholder="${cur||''}"></label><label class="field" style="margin:0"><span>Waist (cm)</span><input class="inp" id="wwa" type="number" inputmode="decimal" placeholder="—"></label><label class="field" style="margin:0"><span>Body fat %</span><input class="inp" id="wbf" type="number" inputmode="decimal" placeholder="—"></label></div>
 <button class="btn full" style="margin-top:10px" data-act="wAdd">Save today’s entry</button>${ws.length?`<div style="margin-top:8px">${[...ws].reverse().slice(0,5).map(w=>`<div class="li"><span class="grow sm">${dlabel(w.d)}</span><span class="b">${w.kg} kg</span>${w.waist?`<span class="sm mut">${w.waist} cm</span>`:''}${w.bf?`<span class="sm mut">${w.bf}%</span>`:''}<button class="iconbtn" style="width:32px;height:32px" data-act="wDel" data-d="${w.d}" aria-label="Delete">${ic('x',14)}</button></div>`).join('')}</div>`:''}</div></div>`}
ACT.wAdd=()=>{const kg=+$('#wkg').value;if(!(kg>20&&kg<300))return toast('Enter your weight in kg');const w={d:today(),kg:r1(kg)},wa=+$('#wwa').value,bf=+$('#wbf').value;if(wa)w.waist=wa;if(bf)w.bf=bf;S.weights=S.weights.filter(x=>x.d!==w.d).concat(w);S.me.wt=r1(kg);save();render();toast('Weight saved')};
ACT.wDel=t=>{S.weights=S.weights.filter(w=>w.d!==t.dataset.d);save();render()};
CHG.me=t=>{const k=t.dataset.k;S.me[k]=t.type==='number'?(t.value===''?'':+t.value):t.value;save();if(['wt','ht','age'].includes(k)&&k)toast('Saved — tap “Recalculate” to update targets')};
CHG.tg=t=>{S.tg[t.dataset.k]=+t.value||0;save()};
CHG.ui=t=>{S.ui[t.dataset.k]=t.checked;save();render()};CHG.sched=t=>{S.sched.on=t.checked;save();render()};CHG.schedX=t=>{S.sched.extra=Math.max(0,Math.min(1000,+t.value||0));save();render()};
ACT.meSet=t=>{const k=t.dataset.k,v=t.dataset.v;if(k==='fastPlan'){S.fast.plan=v}else S.me[k]=['pace'].includes(k)?+v:v;save();render()};
ACT.meTog=t=>{const k=t.dataset.k,a=S.me[k]||(S.me[k]=[]),i=a.indexOf(t.dataset.v);i>=0?a.splice(i,1):a.push(t.dataset.v);save();render()};
ACT.themeSet=t=>{const v=t.dataset.t;S.ui.theme=v;if(v==='auto')delete document.documentElement.dataset.theme;else document.documentElement.dataset.theme=v;save();render()};
ACT.recalc=()=>{const me=S.me;if(!(me.age&&me.ht&&me.wt))return toast('Add age, height and weight first');const t=calcTargets(me);Object.assign(S.tg,{kcal:t.kcal,p:t.p,c:t.c,f:t.f,fib:t.fib,water:t.water});save();render();toast('Targets updated: '+fmt(t.kcal)+' kcal · '+t.p+' g protein')};
ACT.resetAll=()=>{if(confirm('Erase your whole log, foods, meals and settings from this browser? This can’t be undone.')){try{localStorage.removeItem(KEY)}catch(e){}S=Object.assign(defState());save();vd=today();render();startOnboarding()}};

/* ============ ONBOARDING ============ */
let OB=null;
const OBTIPS={out:'Eating out & street food: use the Look-alikes guide and log restaurant dishes before you eat.',night:'Late-night snacking: Insights → Timing shows how much lands after 8 PM.',sweet:'Mithai cravings: log by the piece — one gulab jamun is ~150 kcal.',skip:'Skipping meals: save your usual meals for one-tap logging.',portion:'Big portions: pick katori sizes when you log — your own katori beats guessing.',fest:'Festivals & weekends: turn on “Weekly rhythm” to plan extra for weekends.',chai:'Sugary chai: log tea with milk and sugar — a few cups add up.',protein:'Protein: watch the big pink number on Home — paneer, dal, eggs, soya and curd help.'};
function startOnboarding(){OB={i:0,d:{name:'',goal:null,sex:null,age:'',ht:'',wt:'',tw:'',pace:.5,act:null,diet:null,allergy:[],obst:[]}};renderOB()}
const obSteps=()=>['welcome','goal','body',...(['lose','gain'].includes(OB.d.goal)&&OB.d.age>=18?['pace']:[]),'act','diet','obst',...(CFG?['perm']:[]),'plan'];
function renderOB(){const d=OB.d,st=obSteps(),cur=st[OB.i],w=$('#obw');let body='',btn='Continue';
 const opt=(k,v,l,s)=>`<button class="big-opt ${(Array.isArray(d[k])?d[k].includes(v):d[k]===v)?'on':''}" data-act="${Array.isArray(d[k])?'obTog':'obSet'}" data-k="${k}" data-v="${v}"><span class="grow">${l}${s?`<small>${s}</small>`:''}</span></button>`;
 if(cur==='welcome'){body=`<div class="c" style="margin:28px 0 20px">${art(F('nthali'),110)}<h1 style="margin-top:12px">Welcome to Bitewise</h1><p class="mut">The calorie & protein tracker built around Indian food — katoris, rotis and chai included. A few quick questions to set your daily targets.</p></div><label class="field"><span>What should we call you?</span><input class="inp" id="obn" value="${esc(d.name)}" placeholder="Your name" data-in="obName"></label>`;btn='Let’s begin'}
 if(cur==='goal'){body=`<h1>What’s your goal?</h1><p class="mut">This sets your calorie target.</p>${opt('goal','lose','Lose weight','Gentle calorie deficit')}${opt('goal','maintain','Maintain my weight','Eat at your daily need')}${opt('goal','gain','Gain weight','Small calorie surplus')}${opt('goal','muscle','Build muscle','Surplus + higher protein')}`}
 if(cur==='body'){const g=d.goal;body=`<h1>About you</h1><p class="mut">Used only for the calorie formula. Stays in this browser.</p><div class="field"><span>Sex</span><div class="opts">${[['f','Female'],['m','Male'],['o','Other']].map(([v,l])=>`<button class="opt ${d.sex===v?'on':''}" data-act="obSet" data-k="sex" data-v="${v}">${l}</button>`).join('')}</div></div><div class="grid2"><label class="field"><span>Age</span><input class="inp" type="number" inputmode="numeric" value="${d.age}" data-in="obf" data-k="age"></label><label class="field"><span>Height (cm)</span><input class="inp" type="number" inputmode="numeric" value="${d.ht}" data-in="obf" data-k="ht"></label><label class="field"><span>Weight (kg)</span><input class="inp" type="number" inputmode="decimal" value="${d.wt}" data-in="obf" data-k="wt"></label>${g==='lose'||g==='gain'?`<label class="field"><span>Target weight (kg)</span><input class="inp" type="number" inputmode="decimal" value="${d.tw}" data-in="obf" data-k="tw"></label>`:''}</div>${d.age&&d.age<18?'<div class="note sm" style="margin-top:12px">These estimates are meant for adults. Under 18, please talk to a parent and doctor about food and weight — we’ll set a maintenance target.</div>':''}`}
 if(cur==='pace'){body=`<h1>How fast?</h1><p class="mut">A slower pace is easier to keep up.</p>${opt('pace',.25,'Easy · 0.25 kg / week','Most flexible')}${opt('pace',.5,'Steady · 0.5 kg / week','Recommended for most people')}${opt('pace',.75,'Faster · 0.75 kg / week','Needs consistency — go slower if you feel tired')}`}
 if(cur==='act'){body=`<h1>How active are you?</h1><p class="mut">Think of a typical day, not workouts alone.</p>${Object.entries(ACTL).map(([k,v])=>opt('act',k,v[0],v[1])).join('')}`}
 if(cur==='diet'){body=`<h1>What do you eat?</h1><p class="mut">We’ll tailor food ideas.</p>${opt('diet','veg','Vegetarian','No egg, fish or meat')}${opt('diet','egg','Eggetarian','Vegetarian plus eggs')}${opt('diet','nv','Non-vegetarian','Everything')}<div class="field"><span>Anything to avoid? (optional)</span><div class="opts">${[['gluten','Gluten'],['lactose','Lactose'],['nuts','Nuts'],['jain','Onion-garlic free']].map(([v,l])=>`<button class="opt ${d.allergy.includes(v)?'on':''}" data-act="obTog" data-k="allergy" data-v="${v}">${l}</button>`).join('')}</div></div>`}
 if(cur==='obst'){body=`<h1>What gets in the way?</h1><p class="mut">Pick any — we’ll give you a tip for each.</p>${[['out','Eating out & street food'],['night','Late-night snacking'],['sweet','Mithai / sweet cravings'],['skip','Skipping meals'],['portion','Big portions'],['fest','Festivals & weekend meals'],['chai','Sugary chai & coffee'],['protein','Not enough protein']].map(([v,l])=>opt('obst',v,l)).join('')}`;btn='See my plan'}
 if(cur==='perm'){body=`<h1>Log faster</h1><p class="mut">Turn on what you’d like — change it anytime in Profile. Photo upload and search always work without any permission.</p><div class="card" style="padding:4px 12px">${permCard()}</div><p class="xs mut" style="margin-top:12px">Photos and voice text you choose to analyze are sent to our AI service to identify the food. They aren’t stored on our server.</p>`}
 if(cur==='plan'){const me=obMe(),t=calcTargets(me),wk=planWeeks(me),under=me.tw&&me.ht&&me.tw/((me.ht/100)**2)<18.5;body=`<h1>${d.name?esc(d.name)+', your':'Your'} plan</h1><p class="mut">Estimates to start with — adjust anytime.</p>
  <div class="card c"><div class="mut sm b" style="letter-spacing:.06em;text-transform:uppercase">Daily calorie budget</div><div class="num" style="font-size:60px;line-height:1">${fmt(t.kcal)}</div><div class="sm mut">kcal · your body burns about ${fmt(t.tdee)} a day</div></div>
  <div class="grid3" style="margin-top:10px"><div class="stat c"><b class="num" style="color:var(--pro)">${t.p} g</b><span>Protein</span></div><div class="stat c"><b class="num">${t.c} g</b><span>Carbs</span></div><div class="stat c"><b class="num">${t.f} g</b><span>Fat</span></div></div>
  ${wk?`<div class="card" style="margin-top:10px"><b>About ${wk} weeks</b> to go from ${me.wt} kg to ${me.tw} kg at ${me.pace} kg a week — around ${dlabel(addDays(today(),wk*7))}.</div>`:''}${under?'<div class="note sm" style="margin-top:10px">Your target weight is in the underweight range. Consider a higher target or check with a doctor.</div>':''}${me.goal==='lose'&&t.kcal<=(me.sex==='m'?1500:1200)?'<div class="note sm" style="margin-top:10px">This is the minimum we suggest — for a bigger deficit, please involve a doctor or dietitian.</div>':''}
  ${d.obst.length?`<div class="card" style="margin-top:10px"><b>Your focus</b>${d.obst.map(o=>`<p class="sm" style="margin:6px 0 0">• ${OBTIPS[o]}</p>`).join('')}</div>`:''}
  <div class="field"><span>Also track (optional)</span><div class="opts">${[['water','Water'],['weight','Weight'],['fast','Fasting timer']].map(([k,l])=>`<button class="opt ${S.ui[k]?'on':''}" data-act="obUi" data-k="${k}">${l}</button>`).join('')}</div></div>
  <p class="xs mut" style="margin-top:12px">Targets are general estimates (Mifflin-St Jeor + activity), not medical advice.</p>`;btn='Start tracking'}
 w.innerHTML=`<div class="ob"><div class="in"><div class="row sp"><div class="dots grow">${st.map((_,i)=>`<i class="${i<=OB.i?'on':''}"></i>`).join('')}</div>${cur!=='welcome'?'':`<button class="sm mut" style="margin:0 0 14px 12px" data-act="obSkip">Skip</button>`}</div><div class="grow">${body}</div><div class="row" style="margin-top:18px">${OB.i>0?`<button class="btn ghost" data-act="obBack">Back</button>`:''}<button class="btn grow" data-act="obNext">${btn}</button></div></div></div>`}
function obMe(){const d=OB.d,age=+d.age||30;return{name:d.name,goal:age<18?'maintain':d.goal||'maintain',sex:d.sex||'o',age,ht:+d.ht||165,wt:+d.wt||65,tw:+d.tw||0,pace:+d.pace||.5,act:d.act||'l',diet:d.diet||'nv',allergy:d.allergy,obst:d.obst}}
INP.obName=t=>{OB.d.name=t.value};INP.obf=t=>{OB.d[t.dataset.k]=t.value;if(t.dataset.k==='age'&&(+t.value>0&&+t.value<18)!==OB.minor){OB.minor=+t.value>0&&+t.value<18;renderOB();const i=$('input[data-k=age]');i.focus()}};
ACT.obSet=t=>{const k=t.dataset.k;OB.d[k]=k==='pace'?+t.dataset.v:t.dataset.v;renderOB()};ACT.obTog=t=>{const a=OB.d[t.dataset.k],i=a.indexOf(t.dataset.v);i>=0?a.splice(i,1):a.push(t.dataset.v);renderOB()};
ACT.obUi=t=>{S.ui[t.dataset.k]=!S.ui[t.dataset.k];renderOB()};ACT.obBack=()=>{OB.i=Math.max(0,OB.i-1);renderOB()};
ACT.obSkip=()=>{S.me={name:OB.d.name,goal:'maintain',sex:'o',age:30,ht:165,wt:65,tw:0,pace:.5,act:'l',diet:'nv',allergy:[],obst:[],sw:65};S.weights=[];save();OB=null;$('#obw').innerHTML='';render()};
ACT.obNext=()=>{const d=OB.d,st=obSteps(),cur=st[OB.i];
 if(cur==='goal'&&!d.goal)return toast('Pick a goal to continue');
 if(cur==='body'){if(!d.sex)return toast('Choose an option for sex');if(!(+d.age>=10&&+d.age<=100))return toast('Enter your age');if(!(+d.ht>=100&&+d.ht<=230))return toast('Enter your height in cm');if(!(+d.wt>=25&&+d.wt<=300))return toast('Enter your weight in kg');
  if((d.goal==='lose'||d.goal==='gain')&&+d.age>=18){if(!(+d.tw>=25))return toast('Enter your target weight');if(d.goal==='lose'&&+d.tw>=+d.wt)return toast('Target should be below your current weight');if(d.goal==='gain'&&+d.tw<=+d.wt)return toast('Target should be above your current weight')}}
 if(cur==='act'&&!d.act)return toast('Choose your activity level');if(cur==='diet'&&!d.diet)return toast('Choose what you eat');
 if(cur==='plan'){const me=obMe(),t=calcTargets(me);me.sw=me.wt;S.me=me;S.tg={kcal:t.kcal,p:t.p,c:t.c,f:t.f,fib:t.fib,water:t.water};S.weights=[{d:today(),kg:me.wt}];save();OB=null;$('#obw').innerHTML='';render();return}
 OB.i++;renderOB();$('.ob')?.scrollTo(0,0);if(obSteps()[OB.i]==='perm')refreshPerm().then(()=>OB&&renderOB())};


/* ============ PERMISSIONS, INSTALL, BACKUP (hosted app) ============ */
const PERM={cam:'unknown',mic:'unknown'};
async function refreshPerm(){if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){PERM.cam=PERM.mic='unavailable';return}
 for(const[k,n]of[['cam','camera'],['mic','microphone']]){try{const s=await navigator.permissions.query({name:n});PERM[k]=s.state;s.onchange=()=>{PERM[k]=s.state;if(OB)renderOB();else if(route==='profile')render()}}catch(e){}}}
ACT.askPerm=async t=>{const k=t.dataset.k;if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)PERM[k]='unavailable';else{try{const s=await navigator.mediaDevices.getUserMedia(k==='cam'?{video:{facingMode:'environment'}}:{audio:true});s.getTracks().forEach(x=>x.stop());PERM[k]='granted'}catch(e){PERM[k]=(e.name==='NotAllowedError'||e.name==='SecurityError')?'denied':'unavailable'}}OB?renderOB():render()};
function permCard(){const row=(k,ttl,why)=>{const s=PERM[k];return`<div class="li"><div class="grow"><b>${ttl}</b><br><span class="xs mut">${why}</span></div>${s==='granted'?'<span class="badge ok">On</span>':s==='denied'?'<span class="badge warn">Blocked</span>':s==='unavailable'?'<span class="badge">Not available</span>':`<button class="btn sm" data-act="askPerm" data-k="${k}">Allow</button>`}</div>${s==='denied'?`<p class="xs mut" style="margin:0 0 8px">Blocked in your browser or phone settings. Open the site/app settings (lock icon by the address bar, or Settings → Bitewise) and switch ${k==='cam'?'Camera':'Microphone'} on.</p>`:''}`};
 return row('cam','Camera','Scan barcodes live. (Photo upload works without this.)')+row('mic','Microphone','Log meals by voice. Your browser’s speech service turns speech into text (Google in Chrome, Apple on iPhone).')}
let DEFERRED=null;const isStandalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone||!!window.Capacitor;const isIOS=()=>/iphone|ipad|ipod/i.test(navigator.userAgent);
function installBanner(){if(!CFG||isStandalone()||S.ui.installHide||!(DEFERRED||isIOS()))return'';return`<div class="card note" style="margin:8px 0"><div class="row"><div class="grow sm"><b>Install Bitewise</b><br>Add it to your home screen for one-tap logging${isIOS()&&!DEFERRED?' — tap Share, then “Add to Home Screen”':''}.</div>${DEFERRED?'<button class="btn hal sm" data-act="install">Install</button>':''}<button class="iconbtn" style="width:34px;height:34px" data-act="installHide" aria-label="Dismiss">${ic('x',16)}</button></div></div>`}
ACT.install=async()=>{if(!DEFERRED)return;DEFERRED.prompt();try{await DEFERRED.userChoice}catch(e){}DEFERRED=null;render()};ACT.installHide=()=>{S.ui.installHide=true;save();render()};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();DEFERRED=e;if(route==='home'||route==='profile')render()});window.addEventListener('appinstalled',()=>{DEFERRED=null;render()});
function dataRows(){const base=[['Food database',`${FOODS.length} Indian foods, typical values`,'ok']];
 if(CFG){const h=HEALTH;if(!h)base.push(['Server','Checking…','warn']);else if(h.error)base.push(['Server','Not reachable — check your connection','warn']);else base.push(['Photo, voice, label & custom-food AI',h.ai?'Connected':'Server has no GEMINI_API_KEY yet',h.ai?'ai':'warn'],['Barcode → product database','Open Food Facts (via server)','ok'],['Custom-food web search','Open Food Facts + Google Search grounding','ok'])}
 else base.push(['Photo, voice, label & custom-food AI','Uses Gemini when the published app is connected','ai'],['Barcode → product database','Open Food Facts adapter · '+({untested:'tries when you scan',connected:'connected',unreachable:'not reachable from this page'})[PROVIDERS.off.status],'warn'],['Live web nutrition search','Uses Google Search during custom-food estimates','warn']);return base}
function dl(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
ACT.exportJson=()=>dl('bitewise-backup-'+today()+'.json',JSON.stringify(S),'application/json');
ACT.exportCsv=()=>{const q=v=>'"'+String(v??'').replace(/"/g,'""')+'"',rows=[['date','time','meal','food','quantity','unit','grams','kcal','protein_g','carbs_g','fat_g','fibre_g','sugar_g','sodium_mg','source']];
 [...S.entries].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).forEach(e=>rows.push([e.date,e.time,e.meal==='custom'?e.cust:MEALNAME[e.meal],e.name,e.qty,e.unit,r0(e.g),r1(e.n.kcal),r1(e.n.p),r1(e.n.c),r1(e.n.f),r1(e.n.fib),r1(e.n.sug),r0(e.n.na),e.src]));dl('bitewise-food-log-'+today()+'.csv',rows.map(r=>r.map(q).join(',')).join('\n'),'text/csv')};
ACT.importPick=()=>$('#impIn').click();
CHG.importJson=async t=>{const f=t.files[0];t.value='';if(!f)return;try{const j=JSON.parse(await f.text());if(!Array.isArray(j.entries)||!j.tg)throw 0;if(!confirm('Replace everything in this app with the backup from '+f.name+'?'))return;S=Object.assign(defState(),j);S.ui=Object.assign(defState().ui,S.ui||{});save();vd=today();render();toast('Backup restored')}catch(e){toast('That file isn’t a Bitewise backup')}};

/* ============ BOOT ============ */
document.addEventListener('click',e=>{const t=e.target.closest('[data-act]');if(t&&ACT[t.dataset.act]){if(t.tagName!=='INPUT')e.preventDefault();ACT[t.dataset.act](t,e)}else if(e.target.id==='ov'){ACT.closeSheet()}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#ov').classList.contains('on'))ACT.closeSheet();if((e.key==='Enter'||e.key===' ')&&e.target.matches('[role=button]')){e.preventDefault();e.target.click()}});
document.addEventListener('input',e=>{const t=e.target.closest('[data-in]');if(t&&INP[t.dataset.in])INP[t.dataset.in](t,e)});
document.addEventListener('change',e=>{const t=e.target.closest('[data-ch]');if(t&&CHG[t.dataset.ch])CHG[t.dataset.ch](t,e)});
window.addEventListener('pagehide',()=>{scanStop();stopVoice()});
(function boot(){if(S.ui.theme&&S.ui.theme!=='auto')document.documentElement.dataset.theme=S.ui.theme;
 const used=new Set();S.entries.forEach(e=>used.add(e.fid));S.meals.forEach(m=>m.items.forEach(i=>used.add(i.fid)));S.learn.hashes.forEach(h=>h.items.forEach(i=>used.add(i.fid)));Object.keys(S.tfoods).forEach(k=>{if(!used.has(k))delete S.tfoods[k]});
 render();if(!S.me)startOnboarding();
 if(CFG){fetch(API+'/api/health').then(r=>r.json()).then(h=>{HEALTH=h;if(route==='profile')render()}).catch(()=>{HEALTH={error:true};if(route==='profile')render()});refreshPerm().then(()=>{if(route==='profile')render()});
  if('serviceWorker' in navigator&&(location.protocol==='https:'||location.hostname==='localhost'))navigator.serviceWorker.register('/sw.js').catch(()=>{});
  const h=location.hash.slice(1);if(S.me){if(['add','photo','scan','history','insights','profile'].includes(h))go(h);else if(h==='voice')setTimeout(()=>ACT.voice(),400)}}})();
